### ISSUE TITLE
Internal links to parts of the Tutorial have confusing naming

### ISSUE THREAD

**Issue by Jason-Lee-Quinn** [django/djangoproject.com#1025]
Working my way through the Documentation's Tutorial, I noticed links to previous parts of the Tutorial are called, eg, "Tutorial 2", "Tutorial 5", etc. Would be better if all links are called eg "Part 2" or "Part 5" since that's how the main page of Documentation introduces them:

Tutorial: Part 1: Requests and responses | Part 2: Models and the admin site | Part 3: Views and templates | Part 4: Forms and generic views | Part 5: Testing | Part 6: Static files | Part 7: Customizing the admin site

This seemingly minor inconsistency of naming is potentially confusing and disorientating because it could the reader think there are multiple tutorials (each with their own parts). When I got to Part 2 of the tutorial, it's lead sentence says "This tutorial begins where Tutorial 1 left off." and my first thought was "Hey, I haven't finished Tutorial 1 yet".

**Comment by carltongibson** [comment]
Hi @Jason-Lee-Quinn. Thanks for the report. 

So, **yes** nice spot, making things consistent here is a good thing. 

This isn't really a ticket for here. The docs live over on https://github.com/django/django. I'm going to close this issue here because of that.

The tickets for Django live on [TRAC (Documentation filter applied)](https://code.djangoproject.com/query?status=assigned&status=new&component=Documentation&col=id&col=summary&col=status&col=owner&col=type&col=component&col=version&desc=1&order=id) — this might just count as a small cleanup so may not need one (at least initally) but you are welcome to open a ticket there if you'd like. 

The [guide for writing documentation is here](https://docs.djangoproject.com/en/3.1/internals/contributing/writing-documentation/). It should tell you everything you need to know to get started. 

If you want to open a PR on Django making your changes that would be great. 
You can @carltongibson me here or there if you need advice. Happy to help get you started. 

Thanks again.
