### ISSUE TITLE
Getting fields from different app models to another

### ISSUE THREAD

**Issue by divyankgarg** [django/djangoproject.com#1057]
We have defined two apps: Manin_matrix and SW_matrix. We want the field name (project_name) present in class GENERAL_t of modle.py file inside Main_matrix app to be inside the models.py file of SW_matrix app. Basically  project_name_work field in class EDVT of SW_matrix models.py should be same as project_name of Main_matrix app. 
We want this so that in database for EDVT table we will get the same project id along with project name.

Main_matrix/models.py
class GENERAL_t(models.Model):
    project_name = models.CharField(blank=True, null=True, max_length=40, verbose_name = 'Project_Name')
    platform = models.CharField(blank=True, null=True, max_length=40, verbose_name = 'Platform SW')

SW_matrix/models.py
class EDVT(models.Model):
    project_rel=models.ForeignKey(GENERAL_t,null=True,on_delete=models.SET_NULL,verbose_name="Choose Project")
    project_name_work = models.ForeignKey(GENERAL_t.project_name, null=True, verbose_name = 'Project_Name')

**Comment by shaib** [comment]
Hi, this place is the bug-tracker for the Django project website. This is not a support channel. You can probably get help about using Django at the Django forum, https://forum.djangoproject.com/

Could you please also elaborate what led you to post your question here, in order to help us make it clearer up-front that this is not an appropriate place for support questions?

**Comment by divyankgarg** [comment]
Thanks for correct link.
