### ISSUE TITLE
Dark theme 

### ISSUE THREAD

**Issue by himanshu007-creator** [django/djangoproject.com#1064]
Django website is simple and good. But what about the health of developers?
As of now, there is no provision for dark theme.Having a dark theme will improve user experience.I would like to work on this issue.

**Comment by Pratikshya1201** [comment]
Would you mind if I work on this issue ? I promise to submit it within a week.

**Comment by himanshu007-creator** [comment]
> Would you mind if I work on this issue ? I promise to submit it within a week.

we can work in collaboration!

**Comment by Pratikshya1201** [comment]
> > Would you mind if I work on this issue ? I promise to submit it within a week.
> 
> we can work in collaboration!

sure :)

**Comment by himanshu007-creator** [comment]
> > > Would you mind if I work on this issue ? I promise to submit it within a week.
> > 
> > 
> > we can work in collaboration!
> 
> sure :)

got linkedin?

**Comment by Pratikshya1201** [comment]
> > > > Would you mind if I work on this issue ? I promise to submit it within a week.
> > > 
> > > 
> > > we can work in collaboration!
> > 
> > 
> > sure :)
> 
> got linkedin?

yes
https://www.linkedin.com/in/pratikshya-mishra-b84b6b1a9/

**Comment by Asday** [comment]
How's it going?

**Comment by himanshu007-creator** [comment]
> How's it going?

Hi @Asday sir, i am having exams rn so couldn't work on it

**Comment by kcoder63** [comment]
can I work on this if its still open ?

**Comment by Asday** [comment]
Please do, my retinas will thank you.

**Comment by yash112-lang** [comment]
Hello @himanshu007-creator, is this issue is still open. I am new to open source & want to contribute.

**Comment by kunals131** [comment]
I want to work on this issue, is it still open?

**Comment by Asday** [comment]
Please, if anyone is reading this - just work on it.  The issue has been open for over a year and keeps dying in the water with people abandoning it without a word and disappearing in a puff of smoke.

It's simple CSS recolouring work.  If anyone was working on it, there would be a PR open in days, if at all that long.

In the meantime, I've written this CSS userscript for docs.djangoproject.com which I have applied with the browser extension Stylus.  It will make any designer recoil in horror, but I don't care because I'm not trying to please them, I'm trying to have working retinas by the time I have children.

```
html {
    filter: invert(100%);
}
```

**Comment by pauloxnet** [comment]
FYI the work on this issue is going on in the PR #1213

**Comment by Asday** [comment]
I'm not familiar with the release cadence of the website - when will #1213 be live?
