### ISSUE TITLE
Add discord reference in Django community page

### ISSUE THREAD

**Issue by pauloxnet** [django/djangoproject.com#1123]
It can be useful to add the URL to join the official Django discord server to the Django Community page:
https://www.djangoproject.com/community/

**Comment by marksweb** [comment]
@pauloxnet What is the official django discord server?

I've only ever seen an unofficial discord server 🤔 

Got a branch ready to put this on if you can share the details 👍

**Comment by knyghty** [comment]
I'm the server "owner" and FTR I don't know if I'd call it "official", just that it's run by mostly DSF people, which I would say is not quite the same thing.

However, I think we're probably at the point where we'd like to ask nicely for this - though probably without sharing the link in public just yet.

**Comment by boxed** [comment]
If that page is an honest attempt at getting help to people maybe link to the server where people get helped? Just an idea 😂

**Comment by knyghty** [comment]
Ok, now it's more public. We don't get our own URL until there's enough activity but we could use this invite link for the moment, if someone wanted to add it: https://discord.gg/xcRH6mN4fa

**Comment by boxed** [comment]
Honest question: why not add a link to the unofficial discord server? It's bigger and more active.

**Comment by knyghty** [comment]
@boxed as has been made clear to you and others on the server, any communities linked from the community page must explicitly adopt to the CoC. The unofficial server was given the opportunity to do so, which they refused, so they won't be.

Quite why you choose to bring this up here again -- and presumably link it for your friends to brigade since your comment on a not very active issue on a not very active repo already has three +1 emojis from people I've never seen active on any django repo before -- is entirely beyond me, unless you're just trying to take cheap shots I suppose 🤷🏻

**Comment by boxed** [comment]
> any communities linked from the community page must explicitly adopt to the CoC

...because?

The question I'm asking, in all honesty, is.. what is the point of the page in question? Is it to honestly help people? To honestly describe the actual community that exists? 

It seems it's not that. So, then the question is what is the point of the page?

**Comment by boxed** [comment]
Does all the blogs you link to on that page implement the CoC for example?

**Comment by knyghty** [comment]
> So, then the question is what is the point of the page?

I didn't add the page, and I don't know who did, but my understanding of its current utility would be that it provides a curated list of communities that adhere to the core principles of the project as the DSF sees fit -- which includes adhering to the CoC. If you don't like this answer, I'm not sure what to tell you. You'd probably have to take your case to whoever would make that decision, presumably the ops team or perhaps the DSF. Either way, this isn't the venue for that discussion.

> Does all the blogs you link to on that page implement the CoC for example?

The blogs are vetted before being added. Some bad actor could presumably add something violating the CoC after this process, just like they could in a chat server break the rules after agreeing to them. Just like on a chat server, this would be a moderation issue and the blog would be pulled once it was noticed.

**Comment by boxed** [comment]
> I didn't add the page, and I don't know who did, but my understanding[...]

> You'd probably have to take your case to whoever would make that decision, presumably the ops team or perhaps the DSF. 

You just guess and yet for me the bar is to appeal to the DSF, but for you it's nothing. Hmm. You just took your guess and now it's law? 


BTW.  I missed this before:

> as has been made clear to you and others on the server, any communities linked from the community page must explicitly adopt to the CoC. 

First of all that's just a straight up lie. No Ken said that to the owner or anyone I know on that server. 

And again, you just admitted that that's not in fact the case. You just made that up.

**Comment by knyghty** [comment]
First of all, I don't really appreciate the hostility. If you don't think you're being hostile, you might consider that you've called me a liar multiple times, and that there may be better ways to make your point or find the truth without resorting to personal attacks. Anyway:

> You just guess

There is a difference between guessing and deducing. Consider:

1. All communities listed on the community page adopt the CoC.
2. All blogs listed in the RSS feed are vetted for CoC violations.

I don't think it's that much of a stretch to say that if you want a spot on the community page, you should adopt the CoC and jump through whatever other hoops are necessary. In fact, the owner of the other server you mention could have, at any point, asked to be listed on the page (via an issue here or otherwise), but chose not too. You can't cry foul that another server should be listed here when they have never asked for it.

> the bar is to appeal to the DSF

Well, yes, of course. I have no authority to change it.

> but for you it's nothing

No, if I also wanted to add something to the community page that doesn't adopt the CoC I'm sure I'd get exactly the same response. The difference is that we went through this process. I _did_ appeal to the DSF to make this happen. The discord server has been around for months in private while we were getting all this stuff sorted out, and for what it's worth, even in its private form, the CoC was adopted from day one. Again, the other server could have done the same thing, and was given ample opportunity to do so. I wasn't personally a part of this, but as I understand it the admins were contacted and they didn't want to adopt the CoC or go through anything else and seemed to be happy with rebranding as explicitly unofficial.

> You just took your guess and now it's law?

No, I took my deduction and provided you with an explanation of why it seems (to me - I could be wrong here, I'm not in charge) that the other server wouldn't be added to the page.

>>as has been made clear to you and others on the server, any communities linked from the community page must explicitly adopt to the CoC.

> First of all that's just a straight up lie. No one said that to the owner or anyone I know on that server.

It's not a straight up lie, but if I was being very generous to you I could stretch to saying it is a bit of a misunderstanding. It's true that I didn't explicitly say that _being added to this page specifically_ was not made clear. However from this conversation you seem to be aware that the CoC is an issue for us with the other Discord:

<img width="668" alt="Screenshot 2022-01-18 at 18 25 52" src="https://user-images.githubusercontent.com/3871354/149987810-9c1c4995-0125-4e72-b52f-dedadb707b96.png">

So it would seem clear to me that you were aware of the situation with the CoC relating to the other server, so I'm not really sure how it's such a big leap to think it wouldn't be added to the page...

> And again, you just admitted that that's not in fact the case. You just made that up.

That's overly hostile, but more importantly, false. I admitted that I don't know the intent of the original author of the page. I did not admit that it is "not in fact the case". As far as I can tell (which, again, may well be wrong but to the best of my knowledge, is not - if you consider that a lie, then, sure, whatever), it is in fact the case.

**Comment by boxed** [comment]
> It's not a straight up lie, but if I was being very generous to you I could stretch to saying it is a bit of a misunderstanding. 

Hmm. But you said 

> as has been made clear to you and others on the server, any communities linked from the community page must explicitly adopt to the CoC.

In fact it has not. In fact it hasn't even been mentioned. At all. 

Not mentioning isn't "made very clear".

If you don't like being called out in a lie, don't tell them, and if you do by mistake, then own the mistake. Don't get angry at me for telling the truth. We all make mistakes. That's fine. 

If I was very generous towards you I could say that you just misspoke. Because what you did say was in fact false. 

We can deescalate this if you want. I do. I hate this stuff. I'm probably gonna lose sleep over this. 

> However from this conversation you seem to be aware that the CoC is an issue for us with the other Discord:

I know that the DSF approached the unofficial server about the trademark issue. And that the DSF CoC would be required if it would want to avoid renaming it. It was decided to rename. This was fine. No one had a problem with this. It was very polite. Really it is required by trademark law to some extent.

**Comment by SimeonAleksov** [comment]
> @boxed as has been made clear to you and others on the server, any communities linked from the community page must explicitly adopt to the CoC. The unofficial server was given the opportunity to do so, which they refused, so they won't be.
> 
> Quite why you choose to bring this up here again -- and presumably link it for your friends to brigade since your comment on a not very active issue on a not very active repo already has three +1 emojis from people I've never seen active on any django repo before -- is entirely beyond me, unless you're just trying to take cheap shots I suppose 🤷🏻

For the record, I'm in both servers, and IMO both servers should be available to the public.

Another thing, I don't see a point in this discussion, after all we all want to write some code, it doesn't matter whether it's in an 'unofficial/more official or an official' server.

**Comment by sarthak0527** [comment]
Hi @pauloxnet , I'm new to community  would like to try to contribute. Can I work on this?
