### ISSUE TITLE
Side-Scrollbar on the website breaks the focus while reading

### ISSUE THREAD

**Issue by RyanWalker277** [django/djangoproject.com#1253]
### Issue

The broad sidebar on the website looks extremely annoying , grabbing the user's attention and breaking the focus while reading the website contents. The sidebar should either be removed completely or minimized so that it doesent grab the user's attention and dosent break the focus ,  while mantaining the ability to scroll.As of now , the issue exists only on chrome and edge browsers.

### Screenshots
Chrome : 

![image](https://user-images.githubusercontent.com/32684077/196532448-1c368592-b249-4257-8a32-c9429263ade4.png)

Edge :

![image](https://user-images.githubusercontent.com/32684077/196533182-78e76d4f-8bc4-4452-9cf1-14f01184a5c6.png)

### Proposed Fix

So , the major problem with hiding side-scrollbars is to retain the ability to scroll. For hiding the scrollbars , `overflow: hidden` can be added to the css but that disables the scrollability of the webpage.The better approach would be to use `-webkit-scrollbar` pseudo selector for webkit browsers like chrome and edge.Just adding the `-webkit-scrollbar` pseudo selector in `djangoproject\scss\_style.scss` would fix the issue.

### Screenshots ( After the Fix )

Chrome:

![image](https://user-images.githubusercontent.com/32684077/196534442-2c5a7e60-e5e9-4688-bdcf-02a8e068d70e.png)

Edge:

![image](https://user-images.githubusercontent.com/32684077/196534360-277e104b-d78e-47c9-b9b0-34f15355a097.png)

**Comment by camilonova** [comment]
I'm not sure how this is actually needed. I think it would depend on each OS/browser's settings.

**Comment by sabderemane** [comment]
Echoing @camilonova , I'm not sure it's actually needed, but If we take in consideration the most annoying part, which is I think the color of the scrollbar, we can change it but it can fallback to the default if [the property is not working on the OS/browser](https://caniuse.com/?search=scrollbar).

IMO, we can't set `overflow: hidden` it's breaking the accessibility to me, we will need to redefine the scrollbar and we shouldn't do that.

**Comment by thibaudcolas** [comment]
We can’t hide the scrollbar because (surprise surprise!) people need it in order to scroll. I’d also advise against customising the scrollbar in any way.

As far as I can tell the scrollbar presence correctly responds to OS-level settings (at least in macOS). Here is a recording with MS Edge in the foreground and Chrome behind:

![scrollbar toggle recording](https://github.com/django/djangoproject.com/assets/877585/fbf95556-0e37-4a56-828e-111c877a2b31)

If the scrollbar doesn’t respond to OS settings in other operating systems due to this site’s implementation, that could be worth investigating, but certainly shouldn’t require us to customise the scrollbar with CSS.

**Comment by camilonova** [comment]
This is a user preference. I'm closing it.
