### ISSUE TITLE
Add a way to let people create requests to add community local events

### ISSUE THREAD

**Issue by sabderemane** [django/djangoproject.com#1524]
The page about local communities (https://www.djangoproject.com/community/local/) was created from a list of communities listed from a common document in a github issue. 

Many communities might have been missed and there are no current process to add them except explicitly asking somewhere to add one. 

short term solution:
- Add a google form in the page to have people answering to the field corresponding to the one to the database with eventual addition questions if required.

long term solution:
- Add a Django form which will populate the database and add a way to moderate the result before to add them live, to be able to accept or reject proposal if needed.

**Comment by thibaudcolas** [comment]
👍 sounds great to have a clearer process for this. If possible I’d recommend finding a way to do this with pull requests instead of Google Forms, so people can easily submit additions, edits, removals of groups. I’d still mean having someone manually add to the DB I assume, but at least the way to triage requests would be simpler?

If not, Google Forms works great too.

**Comment by sabderemane** [comment]
@thibaudcolas could be yes, like creating a template for issue to add a Django community with all the questions and in the page suggest to submit an issue with the link of the GitHub page for that. 
Sound good to you?

**Comment by thibaudcolas** [comment]
Sounds good to me as a first step! We can see how well it works and adjust if needed.

**Comment by thibaudcolas** [comment]
Here we are! [New issue - Community Request](https://github.com/django/djangoproject.com/issues/new/choose)
