### ISSUE TITLE
Building a Thriving Django Community in Lagos

### ISSUE THREAD

**Issue by iamgarriTech** [django/djangoproject.com#1736]
### Name
Django Lagos

### Description
A community for Django enthusiasts, developers, and learners in Lagos. Django Lagos is dedicated to sharing knowledge, collaborating on projects, and providing networking opportunities for anyone passionate about Django. 

### City
Lagos

### Country
Nigeria

### Event or website URL

N/A

**Comment by sabderemane** [comment]
Hi @iamgarriTech, I suggest that you join [Black Python Devs Discord](https://discord.gg/QdaWsqzA), if it's not already the case, you'll meet people who would be happy to help you create it. (There is a channel #nigeria where I talk about the issue) ⭐ 

I'll close the issue since the community currently doesn't exist.
