### ISSUE TITLE
[UI BUG]: Inconsistent Link Styling and Possible Typo in Documentation

### ISSUE THREAD

**Issue by SrisailamKakurala** [django/djangoproject.com#1849]
**Description:**

In the "Contributing documentation" section of the [documentation](https://docs.djangoproject.com/en/5.1/internals/contributing/) page the link django-admin does not have the same red color styling as the other links. Additionally, it reads as "man page," which might be a typo and should potentially be "main page."

**Steps to Reproduce:**

1. visit https://docs.djangoproject.com/en/5.1/internals/contributing/
2. scroll to Contributing documentation section and see the last link

![WhatsApp Image 2024-12-25 at 09 19 04_a5370444](https://github.com/user-attachments/assets/fb6e2306-fb3d-4353-a90d-44636c6bdd2a)

**Comment by SrisailamKakurala** [comment]
Hey @adamzap! Quick question: should I submit issues here on GitHub, or is it better to use the Django ticket tracker? I noticed no one's really raising issues here, so I was wondering if I'm missing something. Should I report all these on the ticket tracker instead?

**Comment by SrisailamKakurala** [comment]
i can't find this file [file in which this bug lies] in djangoproject.com repo ... can anyone please help me with this!! thanks in advance.

**Comment by adamzap** [comment]
Thank you for the report, but I don't think this one is valid. "`django-admin` man page" is referencing the [`man` page](https://en.wikipedia.org/wiki/Man_page) for the `django-admin` command that the `django` package provides. The styling of the command name is intentionally different because it is to be used on the command line.

Regarding where you should raise issues, any issue about the website (https://www.djangoproject.com/) rather than the web framework itself should be raised on this repository. You are making the correct choice!

I know it can be difficult to wait for a response after opening an issue or making another kind of contribution. There's a lot going on with this project. In addition to that, many people are taking a break this time of year. Patience is appreciated!

Thanks for your contribution!

**Comment by SrisailamKakurala** [comment]
thank you for letting me know! 
and Merry Christmas !!
