### ISSUE TITLE
The dev warning at the top of docs pages covers anchor titles

### ISSUE THREAD

**Issue by pkatseas** [django/djangoproject.com#220]
![with](https://cloud.githubusercontent.com/assets/1475609/5473515/e6f05952-8601-11e4-87ab-7a69d4372302.png)

**Comment by matsaman** [comment]
Something like this could be a reliable CSS fix, no JS required:
``` .section > span[id]:first-child { padding-top: 38px; }```

**Comment by matsaman** [comment]
I guess it would be more like this now, reflecting recent changes in the markup:
`.section > span:first-child + span[id] { padding-top: 38px; }`

But you get the idea. Can has? :D

**Comment by matsaman** [comment]
...and now it'd be more like this...
` .section > span:first-child[id] { padding-top: 38px; }`

1. Why is this code so volatile?
2. Can this please get resolved?

**Comment by timgraham** [comment]
You're welcome to submit a pull request. With your change, would the JavaScript be removed?

**Comment by matsaman** [comment]
Well, I would definitely like to be able to test it all so it's perfect, but after going through all the stuff in the README.rst and downloading _over a gigabyte_ (& it's still going), I've decided it's definitely not worth it.

Anyway, it's literally only this bit of CSS (at this particular moment [you guys keep changing the HTML/hierarchy constantly, or it is otherwise inconsistent between pages/sections])...  
`.section > span:first-child + span[id] { padding-top: 38px; }`
...where `padding-top: 38px` should simply match the height of the colored bar at the top, and be applied to whatever meaningless extraneous empty span you're apply the `id` attribute to at the moment instead of applying it to the `h#` element where it should be.

No JavaScript would be required after using this CSS to correct any vertical orientation due to the colored bar at the top (and it would also always work for any situation, instead of only working sometimes).

**Comment by timgraham** [comment]
I guess all that downloading is coming from `update_docs`? We might consider trimming the `djangoproject.com/docs/fixtures/doc_releases.json` file as there's usually no need for someone to build all those documentation versions. You can go into the admin and delete the extras.

**Comment by timgraham** [comment]
I removed unneeded doc releases in 79edf27bd63a89c982d1369cd5e27d7b9699154a.

**Comment by carltongibson** [comment]
This issue doesn't now reproduce for me on Safari or Firefox.
