### ISSUE TITLE
Improve docs search results relevancy

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#244]
Ideas include using Sphinx search or updating Haystack to a more recent version.

see https://code.djangoproject.com/ticket/16011 for discussion.

**Comment by jezdez** [comment]
Hm, turns out all those options aren't really sensible since they preclude actual data in database tables and not like we do right now load the docs' contents from the file system. In that case I think I'll try upgrading Haystack and improve upon that. Seems as if the Xapian backend has recently gotten some love, so maybe it's not all lost.

That said, if Haystack turns out to be too annoying, I could entertain the idea to move to Elasticsearch due to its ease of hosting and neat Python integration (e.g. https://github.com/elasticsearch/elasticsearch-dsl-py)

**Comment by shaib** [comment]
@HonzaKral may be able to help here.

**Comment by HonzaKral** [comment]
I would be happy to help, I would like to be able to promise code but I am not sure I will have the time but I can definitely answer any questions, regarding elasticsearch and help review any approach and code if we decide to go that direction.

I am working on a new library that does part of what haystack did (0) like query building, `Document` abstraction etc. It might be helpful for this.

0 - https://github.com/elasticsearch/elasticsearch-dsl-py

**Comment by jezdez** [comment]
@HonzaKral Awesome, thanks for the offer, I'll try to port our Haystack 1.x code over to 2.x first and see if I get something more usable out of it. In doubt I'd prefer not having to maintain a java installation, but on the other hand my patience with Haystack is thin from past experience.. so let's see how far I get :)

**Comment by HonzaKral** [comment]
@jezdez cool, ping me any time, esp. on irc or just ping me and I will see you there.

**Comment by jezdez** [comment]
(╯°□°）╯︵ ┻━┻

Gonna port this over to use ES directly, I've tried all Haystack backends now and it's really just not working out.

**Comment by olasitarska** [comment]
kill it with :fire:

**Comment by jezdez** [comment]
@HonzaKral I opened #303 if you want to take a look :) I still need to open a PR for the ansible repo to install ES on the server, but my plan is to get this shipped in the coming week
