### ISSUE TITLE
Add model and views for recurring plans

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#361]
This is basically the next step to extent the fundraising after the current campaign. Allow people to sign up for a recurring donation (weekly, bi-weekly, monthly, quarterly, yearly). I think we should offer a good set of defaults so that we don't create a huge amount of plans on Stripe's site that we have a hard time handling in the long run.

This will require views since people want to see which plan they have and they want to cancel it as well.

This will also require sending out emails to those signing up for a recurring plan so that we can give them a <strike>unique URL</strike> an account page to change/cancel their donation plan.

**Comment by timgraham** [comment]
Would it be better to tie recurring donations to GitHub and/or djangoproject user accounts so we aren't relying on security by obscurity regarding the "unique URL" idea -- or am I misunderstanding how this will work?

**Comment by jezdez** [comment]
Yeah, "unique URL" was meant as "per-user account page". Sorry, bad language.

I don't think it would help us if we'd tie recurring donations to GitHub accounts only to be honest, think organizations wanting to do recurring donations, a GitHub account may simply be not something they'd have. So I guess if we'd attach a recurring donation to a auth user object we could catch two birds with one stone, given the fact that we allow sign-in with GitHub via Trac. Would that be okay?

**Comment by timgraham** [comment]
Yea, reusing the existing authentication mechanism was all I was after in my suggestion.

**Comment by jezdez** [comment]
:+1:

**Comment by olasitarska** [comment]
Ok, I spent some time trying to wrap my head around this. Before I will implement this, I'd rather ask you all first :)

Requirements:
- a) we want to keep a current fundraising page as archive and because we don't want to erase donors credits. it is a also a nice success story for future fundraisings.
- b) donation on the current fundraising should be disabled once we open recurring fundraising.
- c) previously I thought we should keep recurring donations on a weekly basis. now I think it should be monthly. most donations come from companies, we want to make it easier for them. one receipt versus four receipt a month means less administrative hassle.
- d) to simplify it, as django heros we should only display companies who have active recurring donations right now. 
- e) we shouldn't not disclose the amount of donation for anyone. sort by amount of donation. donations > $200 have logos visible.
- f) we should have a couple of suggested plans (I suggest keeping the ones we already definied) + custom donation. technically, we can resolve this by creating Stripe plan for each suggested plan and one additional plan for $1. according to [Stripe docs](https://stripe.com/docs/subscriptions#per-user-pricing), we can just add quantity to subscription, so if someone wants to donate $16 every month, we give them plan for $1 with quantity 16. however, we need to test if this will be somehow differently displayed on receipt / statement. 
- g) user should be able to modify their subscription (change credit card, amount of donation, displayed information) or cancel it. 
- h) we need to handle failed payments: sending e-mail to user for each failed payment and remove donor from the website after X failed payments. 

Does this make any sense?

**Comment by timgraham** [comment]
a) Regarding keeping the current page, I think we should just copy the current HTML once we're ready to "archive it" rather than continuing to generate it from the database.
b) Will there still be an option for a one-time donation?
c) Yes, I think monthly makes sense.
d) I guess it's okay. We can see if there's demand for one-time donations to be display as heros for some length of time.
e) okay
f) okay
g) okay
h) okay

**Comment by olasitarska** [comment]
a) I do agree. Any objections from anyone?

b) That's a good point, there should be. But maybe just via donation form on foundation pages? https://www.djangoproject.com/foundation/donate/

d) True! We could probably make them visible for a month? This would be also minimum for recurring donations that would be cancelled / not recurred because of payments failing.

**Comment by jezdez** [comment]
a) I disagree that we should retire the fundraising page and functionality, we shouldn't get rid of the campaign ability for the sake of the recurring donations.

What I had in mind was more along the lines of keeping the ability to run campaigns such as this (e.g. for a Django sprint, another round of fellowship, or something completely new). We should treat this fundraiser campaign as the first campaign (and populate the already existing but unused campaign field with say "fellowship-2015-01") and make the current fundraising start page a list of campaigns that are currently active. If none is active we only show the donation form, with the option for recurrence. Then have a new detail page for a campaign (e.g. "/fundraising/fellowship-2015-01/" that we can point people to in the future) to see who has donated. That way we don't lose all the work we put into this code and would further allow fundraising techniques such as the matching campaign Jacob asked about.

Recurring donations are a lot less public than the campaigns and are more of an extension of the current one-time donation system than an extensions of the campaigns.

b) no, donations on the current fundraiser should *not* be disabled as long as the stretch goals isn't reached, we owe that to the people who have donated so far. that also implies we'll do a final report on the campaign on the blog and announce the closing.

maybe we should turn the campaign_name field into an own model to be able to enable/disable campaigns easily?

c) Yeah, weekly seems too little, maybe have the options: monthly, quarterly, annual? And add a help text to get in touch with us in case of an unusual interval?

d) No, we should not hide one-time donation heroes, as their donation is still valuable and requires the same attention and praise as companies – we should not create a two-class system here. Simply list the one-time donations by date (if the donors want) and we should be good.

e) "we shouldn't not disclose the amount of donation for anyone. sort by amount of donation. donations > $200 have logos visible" double negative at the start, what do you mean?

Separating recurring donations visually from the one-time donations would also highlight the difference and not create an atmosphere of "the bigger the amount the more important you are". We're dealing with a global audience here where monetary values differ greatly, so let's keep the random sorting.

f) yeah, that seems to be the strategy documented as well, https://support.stripe.com/questions/how-can-i-create-plans-that-dont-have-a-fixed-price

g) also changing the interval (e.g. monthly > quarterly) and download/resending the receipts

h) that means using the webhooks to listen to the `charge.failed` and `invoice.payment_failed` events that signal a failed payment (https://stripe.com/docs/guides/subscriptions#payment-failures)

**Comment by olasitarska** [comment]
a) Ok, make sense! 

b) Yes, I totally agree that we will wait until stretch goal is reached, sorry for not making that more clear. I agree with you here.

c) Why not. I'm just worried that we're making it too complicated. On the other hand, we're still not quite sure how we can reach The Big Corps™, so I'm willing to experiment with that. 

d) How is that fair for organizations who donate on monthly basis? I'm all for giving all the possible credits to people who donate, but I am sure that this time we need to find a way to do it right :)

e) We shouldn't disclose amounts is what I meant. Sorry :) 

Regarding **d** and **e**. I guess we could display everyone with a random order without disclosed amounts. This is a perfectly fine solution. One thing that worries me (and hopefully I am totally wrong here): companies donate more money to be more visible on the website (higher on the list, logo bigger, etc). By making this system work like I described in the first sentence, we don't encourage them to donate more or donate on a more recurring basis. Hopefully we don't have to worry about it at all, because these companies care about Django and just want to do the right thing by donating as much as they can. Are we willing to try?

**Comment by olasitarska** [comment]
Just to follow up to this discussion. We skyped with @jezdez and came to conclusion that:

- we should treat one time donation equally to recurring ones.
- donors should be sorted by a sum of past donations. amount shouldn't not be disclosed.
- we will divide donors into two categories: organizations and individuals and list them in two columns next to each other. we think this is a good way to show that we believe that help from *everyone* is equally valuable, even though obviously companies manage bigger budgets and can donate more.

**Comment by olasitarska** [comment]
I added a milestone and issues based on the discussion here. https://github.com/django/djangoproject.com/milestones/Recurring%20Fundraising
