### ISSUE TITLE
Large payload for fundraising page

### ISSUE THREAD

**Issue by treyhunner** [django/djangoproject.com#364]
The [fundraising page][] requires a 4MB network transfer, mostly due to all of the images on that page.

The 5 largest avatars take up 2MB on their own and some are 1000 x 1000 pixels.

Some things that might help:

- Enable gzip/deflate encodings for smaller network transfer size
- Use [easy-thumbnails][] to create small thumbnails

[easy-thumbnails]: https://github.com/SmileyChris/easy-thumbnails
[fundraising page]: https://www.djangoproject.com/fundraising/

**Comment by jezdez** [comment]
Gzip is enabled for files where it makes sense, basically text based files. I don't think it's common practice to enable it for image files. But I agree that thumbnailing the images to a sensible size makes sense. I'm a bit reluctant to add easy-thumbnails though since I'm not certain about its maintenance status. I think sorl-thumbnail is nowadays better supported and works on 1.7 and Python 3: https://github.com/mariocesar/sorl-thumbnail

**Comment by treyhunner** [comment]
Yes I forgot about the inefficiency of compressing images. It does seem like sorl-thumbnail is the best solution.
