### ISSUE TITLE
1.7.4 Release notes page warns that the document is for Django's development version

### ISSUE THREAD

**Issue by lgp171188** [django/djangoproject.com#369]
https://docs.djangoproject.com/en/dev/releases/1.7.4/ page has this issue. Don't think the release notes is a development version document.

**Comment by lgp171188** [comment]
![release notes page bug](https://cloud.githubusercontent.com/assets/218870/5942095/4e8db820-a73b-11e4-9d56-082f98ba414b.png)
Please see this attached screenshot illustrating the problem.

**Comment by carljm** [comment]
Thanks for the report! The release-notes pages are versioned just like the rest of the docs. You can see the `en/dev` in the URL - you are viewing the Django 1.7.4 release notes in the dev version of the docs. It's true that, unlike other types of doc pages, if the `en/dev` version of the 1.7.4 release notes differed from the `en/1.7` version of those same release notes, that would probably be a bug (those release notes should never change significantly after 1.7.4 is released). But I don't think we are otherwise going to special-case release-note pages for the version handling, so closing this.

**Comment by lgp171188** [comment]
I reached the URL by clicking the links referenced in the release announcement blog post - https://www.djangoproject.com/weblog/2015/jan/27/bugfix-releases-issued/ which links to the dev documentation for 1.7.4 and 1.4.19 release changelog. It would be great if that was fixed to point to the appropriate major version.

I will raise a separate issue for it, if required.

**Comment by carljm** [comment]
@timgraham Would it make sense to change those URLs to point to the stable instead of dev docs?

**Comment by timgraham** [comment]
My thought was that at some point the specific versions of the docs might be removed (1.2 and older are gone now) so this way we won't have to fix broken links if that happens at some point in the future.

**Comment by timgraham** [comment]
Oh, but sure, stable should work.
