### ISSUE TITLE
CSRF doc redirect not working

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#393]
There's a redirect for https://docs.djangoproject.com/en/dev/ref/contrib/csrf/ to /en/dev/ref/csrf/ setup here: https://www.djangoproject.com/admin/redirects/redirect/5/

But it's no longer working. Possibly the addition of django-hosts is related?

**Comment by timgraham** [comment]
@jezdez any idea on this? I can investigate further if needed.

**Comment by jezdez** [comment]
Hmm, let me think. Yeah, the issue here is that the redirects app uses the sites app ability to return the "current site" which in the <1.8 doesn't take the request host into account as implemented in https://github.com/django/django/commit/32c7d3c061b83e9206ef2bf13fbc302a1998f317. I've been meaning to backport that to django-hosts and monkey patch the method on older Django versions (yuck, I know).

The short team solution (that I just enabled) is to make the redirect use the site with the SITE_ID of 1, which is www.d.c. This will auto fix itself once we move to 1.8 though.

**Comment by bmispelon** [comment]
Looks like it's working now. :hammer:
