### ISSUE TITLE
Improve display of heros (currently rendered in a narrow column which doesn't look great)

### ISSUE THREAD

**Issue by jezdez** [django/djangoproject.com#508]
![screen shot 2015-08-10 at 16 27 26](https://cloud.githubusercontent.com/assets/1610/9173853/0fc28140-3f7d-11e5-81e1-b74b3d10bdfa.png)

**Comment by olasitarska** [comment]
So that is because we split individuals and organizations into two columns. Everything is ordered by money donated now, but organizations usually donate much more than individuals. That does look weird, because beside splitting it into two, we haven't provide any other header, or something that makes it clear, which is an issue.

**Comment by timgraham** [comment]
I would consider some sort of "Most Recent Donations" display (sort by date and limit to last 90 days or so) and scrap sorting by amount and individual vs. type. Otherwise, it seems the size of this page will grow forever.

**Comment by timgraham** [comment]
@adriennefriend, how do you think the donors should be organized? I think at least adding a few more tiers like "Gold/Silver/Bronze" or whatever should be done.

**Comment by adriennefriend** [comment]
Thanks for bringing me into this conversation! Ola mentioned that currently everything is organized by money given now, but that isn't actually clear. 

I will need to give some thought to what Gold/Silver/Bronze (or some version of it) might equate to financially, so unfortunately I can't fully answer now.

**Comment by timgraham** [comment]
Should we address this before launching the next round of fundraising?

**Comment by adriennefriend** [comment]
Yes, definitely.

**Comment by adriennefriend** [comment]
Hi Tim, is this possible:

Currently, we post pictures/logos when people give over $200. I would like to encourage more significant gifts by featuring our leadership level donors in a separate section at the top, titled "Leadership Level Donors: $1000 & More"

People who gave less than $1000 will also be recognized, but below the leadership-level donors, in a section that is called "Django Heroes".

**Comment by timgraham** [comment]
Yes, how about breaking it out by level (platinum, gold, etc.) (assuming we proceed with that idea) and also making the logos a different size for each level?

Do you agree to display donations made in the last 365 days? If so, then the level will be determined by the total amount of donations during that period (e.g. a recurring donation of $1,000/month wouldn't immediately be displayed as if that donor gave $12,000/year so that the recurring donations won't be abused through cancellation).

Do you think we need the "Organization" vs. "Individuals" distinction we have now?

**Comment by adriennefriend** [comment]
Hey there Tim, sorry for the delay. Seems like I owe you some clarifications.

So, on the main fundraising page, I need five different sections, in this order of display on the page:

Platinum Corporate Members
Gold Corporate Members
Silver Corporate Members
Django Leaders (Heroes who donate over $1000 in a year) - corporations AND invidiausl
Django Heroes (all donors of any amount) - corporations AND individuals

Is that doable? Not necessary to show in different sizes, unless you think that would look good!

Finally, yes, agreed to display all donors in the yearly "campaign". To simplify, if they're a corporate member (which I can confirm with you), their logo will appear in that section. (If we have no corporate members at a particular level, we'll just leave it off til we have one. No need to say "Platinum Corporate Members" if we have none).

Everyone else will either be a "Django Leader" or a "Django Hero". Whether someone gives $1000 or $12,000 in a calendar year, they will always be a Django Leader.

Anyone who gives $999 or less will be a Django Hero *until* they've given beyond that point, then they'll be "promoted" into Django Leader.

Let me know if you have any questions and I'll try to get back to you soon - I went over my hours last week and I've had a cold!
