### ISSUE TITLE
Heart does not effectively show progress

### ISSUE THREAD

**Issue by adriennefriend** [django/djangoproject.com#562]
In issue 480, Tim shared that heart graphic starts off all white and turns pink as we receive donations. https://github.com/django/djangoproject.com/issues/480 

However, this was not obvious to me. While I personally like the heart graphic, in its current state it does not show progress clearly. Progress should be presented more clearly (see below for an example), but hopefully we can still find a way to present it in a fun way. 

![campaign1](https://cloud.githubusercontent.com/assets/3959233/11487320/3ca6383e-978c-11e5-84e6-3b4a029424cd.jpg)

**Comment by timgraham** [comment]
@treyhunner, want to try to come up with an alternative or rework the heart a bit?

**Comment by adriennefriend** [comment]
I like the heart and would be in favor of keeping it if progress could be shown a little more clearly.

**Comment by treyhunner** [comment]
I agree that the heart fill-up isn't very clear.

One of my first approaches was to fill the heart bottom-up.  That didn't seem clear enough to me initially (though I don't think I've tried it again since the final semi-faded design).

I went with a random fill approach, but that didn't seem to indicate that the heart would actually fill over time. The random pixel movement was added in order to demonstrate that the heart was changing and the hover effect was added to show that a pixel wasn't yet full.

Another approach I haven't experimented with yet: slowly pulsing the "already filled" pixels to indicate that the heart is still filling. :heartbeat: 

I can do some brainstorming in regards to alternative progress bars that might be equally fun but may indicate their purpose more clearly. I do fear my suggestions may be a little biased because I don't have fresh eyes right now though. :smile_cat: 

Here's the original heart progress bar pull request, for context: #312.

**Comment by adriennefriend** [comment]
Thanks for your thoughtful response, Trey, and for taking the time to explain your thinking!

I would be in favor of keeping the heart with revisions to indicate clarity, or of considering other suggestions. Don't worry about bias or old eyes - just let us know what you have in mind, and I'm sure we'll find something we all love. :smile_cat: Thanks for your work!

**Comment by adriennefriend** [comment]
@treyhunner Wondering if you had any thoughts on this? :) We're looking at launching our new fundraiser on Wednesday, December 16, and would love to have the new graphic in place before then. Let me know if you have any questions or want to talk anything through!

**Comment by treyhunner** [comment]
I tried making the faded (unfilled) pixels pulse on a 2 second interval with a random delay to make it sort of look like the heart is sparkling (instead of just uniformly pulsing). It certainly adds more movement but I'm not sure that conveys the idea that those cells are empty. I also think this animation combined with the moving filled pixels might be too much.

Animation: https://youtu.be/6kRZflSzgyo
Code changes: https://github.com/django/djangoproject.com/compare/master...treyhunner:pulsing-heart

I thought about superimposing the percentage over the heart or putting text over the faded tiles, but I think that feel a little crowded.

Thoughts? Ideas?

**Comment by adriennefriend** [comment]
Hi Trey - want to ease your concern that superimposing the percentage over the heard or putting text over the tiles would make it look crowded. Could I see a basic version of that?

Thanks so much for your thoughtful work!

**Comment by treyhunner** [comment]
@adriennefriend I added a text overlay to see what it might look like: https://github.com/django/djangoproject.com/compare/master...treyhunner:pulsing-heart

The text is roughly centered, very large, and includes an different stroke (outline) and fill colors... ideally to make it more readable on a variety of backgrounds. I think the pixels make it a little heard to read.

![selection_627](https://cloud.githubusercontent.com/assets/285352/11679576/d36dd184-9e06-11e5-961b-e4e673e72c7a.png)
![selection_626](https://cloud.githubusercontent.com/assets/285352/11679583/d73e5284-9e06-11e5-8144-5b14b47410cd.png)
![selection_625](https://cloud.githubusercontent.com/assets/285352/11679588/d961a0a2-9e06-11e5-9775-5293ef88d7b8.png)
![selection_623](https://cloud.githubusercontent.com/assets/285352/11679589/dc7756ce-9e06-11e5-96b2-344d66b6323d.png)
![selection_624](https://cloud.githubusercontent.com/assets/285352/11679592/ded4bfd8-9e06-11e5-97f3-e5255b3162b5.png)

**Comment by adriennefriend** [comment]
Agreed to move forward with the text overlay for emphasis. Thank you for your work, @treyhunner !

**Comment by timgraham** [comment]
Hi Trey, on my system the heart looks like this:

![heart](https://cloud.githubusercontent.com/assets/411869/11850359/ce7e251c-a3fa-11e5-9159-0ba5fe0ace0f.png)


What's required to get the more aesthetic font?

**Comment by treyhunner** [comment]
@timgraham very possible that the SVG features I used are not well-supported in all browsers. I'm looking into this in the next couple hours.

**Comment by timgraham** [comment]
Thanks, Ubuntu 14.04 Firefox and Chrome here. I'll be back in a few hours.

**Comment by treyhunner** [comment]
@timgraham I'm guessing this is a problem with the SCSS files not being compiled. It doesn't look like the heart is shimmering either. The font size/color and the shimmer effect are all CSS classes.

**Comment by timgraham** [comment]
Confirmed that the problem exists between chair and keyboard. :-)

**Comment by adriennefriend** [comment]
Thumbs up (from where I sit with Ubuntu 14.04 & Firefox) :)
