### ISSUE TITLE
Production traceback: IndexMissingException[[docs] missing]

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#626]
Since we started rebuilding the docs with a new index each time (https://github.com/django/djangoproject.com/issues/534), I guess an index isn't available while the docs are rebuilding? During this time search suggestions (and maybe searches) don't work.

\cc @bmispelon @HonzaKral

**Comment by HonzaKral** [comment]
Yes, it seems to be the case. The window is fairly small but it is there.

Proper fix is to have versioned indices & an alias. Instead of removing the old index, index all the data into a new index (docs-XYZ) then have an alias `docs` that you can, after a successful indexing of the docs, repoint to the newest version atomically. At that point you can delete the old index safely.

Biggest problem is how to get the index number, but that can be circumvented by using a timestamp instead of an incrementing version number.

Upside of this approach is that the search part doesn't have to change, just the management command.

**Comment by timgraham** [comment]
Could you advise on where the code for this would go? I'm thinking maybe https://github.com/django/djangoproject.com/blob/55c3ac8b09b404051c56e2fa5d168c9a9250440a/docs/search.py#L68-L81 but I'm not familiar with the elastic libraries at all and would like to spend a lot of time barking up the wrong tree if possible.

**Comment by timgraham** [comment]
I think I understand where to put the code now, have started a bit: https://github.com/django/djangoproject.com/pull/635.

**Comment by HonzaKral** [comment]
You are absolutely on the right track to put it into the management command.

Exact commands can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html

**Comment by timgraham** [comment]
Thanks Honza, I left some questions on the pull request. I'm not certain about the best way to translate those HTTP requests into the Python API. Hope you can advise and maybe improve the documentation if you see fit.
