### ISSUE TITLE
fundraising not updated and I don't see my past contributions.

### ISSUE THREAD

**Issue by ashwin31** [django/djangoproject.com#742]
I have funded 2.1k in total (from Jan 1 2017) and my company is being listed in 1000+ section still.
Where can I see the total funding activity of mine, of course I do have email receipts from djangoproject but its better to have those online for future accounting purposes.

I funded on behalf of MicroPyramid

**Comment by timgraham** [comment]
Hi, if you want to be listed as a corporate member, please apply here: https://www.djangoproject.com/foundation/corporate-membership/. We can apply your existing payments rather than invoicing you.

There isn't a place to view to list past donations but this could be added to the `/fundraising/manage-donations/<donor-id>/` view. I've created https://github.com/django/djangoproject.com/issues/743 for that.

Thank you for your support!
