### ISSUE TITLE
Add team editing to member admin

### ISSUE THREAD

**Issue by shaib** [django/djangoproject.com#751]
Currently, the way for a member to change what teams they're listed in is to edit the teams. This is cumbersome and error-prone. Since the member-team relation is M2M anyway, it would be nice to allow a member to control the teams they're in from the member admin.

**Comment by luojiebin** [comment]
It seems that we can't simply add
`    filter_horizontal = ['team_set']`
to IndividualMemberAdmin. Because it will raise an error `admin.E019`.
And we can't do that with ManyToManyField according to [django ticket #897](https://code.djangoproject.com/ticket/897).

Is it better to use two ForeignKey to replace ManyToManyField between member and team, and add team editing to member admin?

**Comment by timgraham** [comment]
No, I don't think it's worth changing the data model to address this issue. Since teams rarely change, it's not very high priority, IMO.
