### ISSUE TITLE
Django 2.1.5 and MySQL Client Incompabilities

### ISSUE THREAD

**Issue by DheerajKN** [django/djangoproject.com#859]
I am using Django 2.1.5 and installed mysqlclient for my application, but when I am running python manage.py migrate. I am getting a whole lot of SQL syntax errors.

So what is the compatible mysqlclient version for Django==2.1.5

**Comment by felixxm** [comment]
This is the repository for the Django's project website, not Django itself. Please see [FAQ: Getting Help](https://docs.djangoproject.com/en/2.1/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help).

Due to the `mysqlclient` you will find answer in the [documentation](https://docs.djangoproject.com/en/2.1/ref/databases/#mysql-db-api-drivers).
