### ISSUE TITLE
List of fellows on the fundraising page is outdated.

### ISSUE THREAD

**Issue by felixxm** [django/djangoproject.com#922]
List of fellows on the [fundraising page](https://www.djangoproject.com/fundraising/) is outdated. I replaced Tim as a full-time Fellow in April, 2019 (see https://www.djangoproject.com/weblog/2019/jan/29/dsf-welcomes-mariusz-felisiak-its-newest-fellow/).

**Comment by carltongibson** [comment]
If you want to draft a bio block, I’m happy to review. 🙂

**Comment by wsvincent** [comment]
How's this y'all? I can submit as proper PR once we agree on wording.
----------------

Who are the Django Fellows?

Currently there are two Django Fellows.

Carlton Gibson (2018-present) - a longtime Django user, core contributor to Django REST Framework, maintainer of Django Filter and Django Crispy Forms, co-host of the DjangoChat weekly podcast, and a contributor to many other packages in the Django ecosystem. Carlton began as a part-time Fellow in 2018.

Mariusz Felisiak (2019-present) - an active contributor to Django, focusing on the ORM and Oracle back-end, along with triaging tickets, reviewing pull requests, and back porting changes. He has contributed to more than  a dozen open-source projects and is a coach for Django Girls Heidelberg.

Emeritus Fellows:

Tim Graham (2015-2018) - the inaugural Django Fellow, a member of the Django team since 2010, and a longtime major contributor and reviewer. In 2018 Tim transitioned to part-time and in 2019 retired after four years of service.

**Comment by carltongibson** [comment]
Hey @wsvincent. Open a PR and we can make edits there.
