### ISSUE TITLE
Why is the auth.User.id field not documented properly?

### ISSUE THREAD

**Issue by creyD** [django/djangoproject.com#934]
On [this page](https://docs.djangoproject.com/en/2.2/ref/contrib/auth/#django-contrib-auth) of the Django documentation the User model is documented and although most of the fields are mentioned, I wonder why there isn't any mention of the automatically incremented user.id field, as this can often be used to identify users.

Is there any specific reason why it's not even mentioned in a note anywhere? The only mention is that the id is always None in the [AnonymousUser Object documentation](https://docs.djangoproject.com/en/2.2/ref/contrib/auth/#anonymoususer-object) on the same page.

If it is documented anywhere else, please just add a link to it on the page so people can find it.

**Comment by frankwiles** [comment]
I think the main reason is that it's a standard field on all models in Django unless specifically overridden to be different.

**Comment by shaib** [comment]
What @frankwiles said --  the `AnonymousUser` documentation does mention the `id` field only because there it is different.

But more generally, this project holds the code and issues for the djangoproject.com website; the Django documentation is managed as part of the Django code, and so, issues about it should be raised on the [appropriate channels](https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/).

**Comment by creyD** [comment]
Okay thank you for your fast response and help! I will close this now and research it further in the other channels.
