### ISSUE TITLE
post_save handlers firing from within a transaction block - desired behavior?

### ISSUE THREAD

**Issue by jon-torodash** [django/djangoproject.com#950]
`django.db.models.base.Model.save_base` performs its save with an atomic transaction, but it then fires the post_save handler after exiting that block without regard as to whether an outer transaction still exists from which `save_base` was called. The real world implications of this are that work in other threads which might be begun before that outer transaction is successfully committed will not see data in the state after those writes.

Now this may be the desired behavior; I could see arguments to be made for both cases, but the in the documentation (https://docs.djangoproject.com/en/2.2/ref/models/instances/#what-happens-when-you-save) it seems to me implied that when `post_save` is fired, that the data is persisted. I don't know offhand how easy it would be to add outer transaction context detection in a compatible non-breaking manner, wherein you could defer post_save to the`__exit__` call if it exists.

Would be grateful if a maintainer could chime in here.

**Comment by shaib** [comment]
Hi @jon-torodash , 

The project where you posted this issue is for the Django project website, not the Django software project. When you raise it in the right place (https://forum.djangoproject.com/ or one of the [mailing lists](https://www.djangoproject.com/community/)) I suggest you present it as a usage problem: "I want to do so-and-so, I run into this-and-that block, how to overcome". 

Multi-threading is almost never easy, but code which behaves differently whether or not it is in a transaction is a strong smell and I find it hard to believe Django will do anything to promote such practices (I am a former member of the Django Technical Team, so this statement comes with some expertise but no authority).
